// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: proto/flight.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AirportServiceClient is the client API for AirportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AirportServiceClient interface {
}

type airportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAirportServiceClient(cc grpc.ClientConnInterface) AirportServiceClient {
	return &airportServiceClient{cc}
}

// AirportServiceServer is the server API for AirportService service.
// All implementations must embed UnimplementedAirportServiceServer
// for forward compatibility
type AirportServiceServer interface {
	mustEmbedUnimplementedAirportServiceServer()
}

// UnimplementedAirportServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAirportServiceServer struct {
}

func (UnimplementedAirportServiceServer) mustEmbedUnimplementedAirportServiceServer() {}

// UnsafeAirportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AirportServiceServer will
// result in compilation errors.
type UnsafeAirportServiceServer interface {
	mustEmbedUnimplementedAirportServiceServer()
}

func RegisterAirportServiceServer(s grpc.ServiceRegistrar, srv AirportServiceServer) {
	s.RegisterService(&AirportService_ServiceDesc, srv)
}

// AirportService_ServiceDesc is the grpc.ServiceDesc for AirportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AirportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AirportService",
	HandlerType: (*AirportServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "proto/flight.proto",
}

// FlightServiceClient is the client API for FlightService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlightServiceClient interface {
	AddFlightIntoAirport(ctx context.Context, in *Flight, opts ...grpc.CallOption) (*Flight, error)
}

type flightServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlightServiceClient(cc grpc.ClientConnInterface) FlightServiceClient {
	return &flightServiceClient{cc}
}

func (c *flightServiceClient) AddFlightIntoAirport(ctx context.Context, in *Flight, opts ...grpc.CallOption) (*Flight, error) {
	out := new(Flight)
	err := c.cc.Invoke(ctx, "/FlightService/AddFlightIntoAirport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlightServiceServer is the server API for FlightService service.
// All implementations must embed UnimplementedFlightServiceServer
// for forward compatibility
type FlightServiceServer interface {
	AddFlightIntoAirport(context.Context, *Flight) (*Flight, error)
	mustEmbedUnimplementedFlightServiceServer()
}

// UnimplementedFlightServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFlightServiceServer struct {
}

func (UnimplementedFlightServiceServer) AddFlightIntoAirport(context.Context, *Flight) (*Flight, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFlightIntoAirport not implemented")
}
func (UnimplementedFlightServiceServer) mustEmbedUnimplementedFlightServiceServer() {}

// UnsafeFlightServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlightServiceServer will
// result in compilation errors.
type UnsafeFlightServiceServer interface {
	mustEmbedUnimplementedFlightServiceServer()
}

func RegisterFlightServiceServer(s grpc.ServiceRegistrar, srv FlightServiceServer) {
	s.RegisterService(&FlightService_ServiceDesc, srv)
}

func _FlightService_AddFlightIntoAirport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Flight)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightServiceServer).AddFlightIntoAirport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FlightService/AddFlightIntoAirport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightServiceServer).AddFlightIntoAirport(ctx, req.(*Flight))
	}
	return interceptor(ctx, in, info, handler)
}

// FlightService_ServiceDesc is the grpc.ServiceDesc for FlightService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlightService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FlightService",
	HandlerType: (*FlightServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddFlightIntoAirport",
			Handler:    _FlightService_AddFlightIntoAirport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/flight.proto",
}
